

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmmirror.com"
# registry : "https://registry.npmmirror.com/"
# electron_mirror: "https://registry.npmmirror.com/-/binary/electron/"

httpProxy: "http://127.0.0.1:10809"

httpsProxy: "http://localhost:10809"
